development:
  adapter: postgresql
  database: doar_development
  host: localhost
  username: doar
  password: doar
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  database: doar_test
  host: localhost
  username: doar
  password: doar
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  database: doar_production
  host: localhost
  username: doar
  password: doar
  encoding: utf8
  pool: 5

